### ISSUE TITLE
Nouvel évènement, des onglets apparaîssent en rouge

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#10]
Depuis ma page de profil (JTest_user),

* Je crée un nouvel évènement, 
* J'introduis quelques données (pas toutes puisque ce sont des tests),
* Je charge une image,
* Je sauve

![2018-02-26_18h25_14](https://user-images.githubusercontent.com/355999/36685022-63d3b7b2-1b22-11e8-8dc4-eee9ee6969af.png)

* Les onglets `contenu` et `images` apparaissent en rouge, je ne sais pas pourqoi.

Image est mon onglet actuel : j'ai une image, j'ai un titre; que dois-je faire ? 

![2018-02-26_18h26_31](https://user-images.githubusercontent.com/355999/36685089-94babfce-1b22-11e8-8f33-9706e8f8cd18.png)

Contenu est en rouge; je ne vois pas ce qui coince (pas immédiatement). Un tag ?  Je teste, je clique sur Association, je sauve et ... j'ai tout perdu, je vois la homepage

![2018-02-26_18h27_40](https://user-images.githubusercontent.com/355999/36685140-bf2fe784-1b22-11e8-8c40-9d961aac9644.png)

Timeout... 

---- Après plusieurs minutes ----

Je recommence, nouvel utilisateur, je sauve autant que faire se peu (le titre, l'image, une date, ...) et patatras, à nouveau ejecté et là, ce n'est plus un timeout. J'ai pris soin de veiller à avoir des interactions avec le site.

Donc : plantages.

**Comment by cavo789** [comment]
Je vois mes évènements en frontend : https://dev-www.joomla.fr/joomla/evenements.

Le système m'ejecte mais il crée donc les évènements...

![2018-02-26_18h57_38](https://user-images.githubusercontent.com/355999/36686502-ea9d0fba-1b26-11e8-9f09-c8b1be33104f.png)

**Comment by sebastienlapoux** [comment]
A tester en production.
