### ISSUE TITLE
404 - https://dev-www.joomla.fr/association/adherer-a-l-association

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#13]
URL 404 https://dev-www.joomla.fr/association/adherer-a-l-association

Source : https://dev-www.joomla.fr/connexion?view=reset, lien "J'adhère à l'AFUJ"

**Comment by sebastienlapoux** [comment]
le bon lien est https://www.joomla.fr/association/adherer .
Merci de cloturer si ok.

**Comment by cavo789** [comment]
Ben oui mais c'est un lien qui est proposé par la page https://dev-www.joomla.fr/connexion?view=reset (comme je l'ai mis), ce n'est pas moi qui l'ai introduit.

Maintenant, la page https://dev-www.joomla.fr/connexion?view=reset est devenue https://www.joomla.fr/connexion?view=reset et là, je vois que le layout n'est plus le même, vous avez supprimé le titre et le lien "J'adhére à l'AFUJ".

*(le transport du site de DEV -version finale- ne correspond donc pas totalement à la version de production)*

**Comment by cavo789** [comment]
Je clôture car le lien a été supprimé depuis lors.
