### ISSUE TITLE
Contenu - Où passer la certification

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#14]
https://dev-www.joomla.fr/joomla/certification/ou-la-passer
Corriger le contenu
![2018-02-26_18h59_32](https://user-images.githubusercontent.com/355999/36686590-2ef10be4-1b27-11e8-85dd-0a4834d71152.png)

**Comment by sebastienlapoux** [comment]
Les pros proposant la certification seront listés en dessous (s'agit d'un test d'un pro avec photo daniel).
Je ne vois pas de contenu à corriger. Merci de préciser et d'assigner le label Equipe rédaction si besoin.

**Comment by cavo789** [comment]
>Je ne vois pas de contenu à corriger.
Ben le fait qu'on voit la photo de Daniel avec un contenu "test sl" me paraîssait clair pourtant. 

Sauf erreur, je n'ai pas, moi, la possibilité d'assigner un label, je n'ai rien dans l'interface qui m'autorise à le faire.
