### ISSUE TITLE
Contenu - Où passer la certification - Pas autorisé

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#15]
Je suis non connecté et j'accède à la page https://dev-www.joomla.fr/joomla/certification/ou-la-passer

Sous la photo de Daniel il y a un lien, je clique dessus et j'ai cet écran

![2018-02-26_19h00_10](https://user-images.githubusercontent.com/355999/36686620-44f25718-1b27-11e8-9686-6e3037a24133.png)

Est-ce logique ?

**Comment by sebastienlapoux** [comment]
Fixé. Merci.
