### ISSUE TITLE
Suggestion - Cookiens - mentions légales - Ancre

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#18]
Le message au bas de la page : "Ce site utilise des cookies pour vous offrir le meilleur service.
En poursuivant votre navigation, vous acceptez l’utilisation de cookies sur ce site. En savoir plus"

"En savoir plus" pointe vers la page "mentions-legales"

Cette page-là contient pourtant une ancre sur <h3 id="cookies">8. Liens hypertextes et cookies.</h3>

Idéalement le lien pourrait être "mentions-legales#cookies"

**Comment by lionelratel** [comment]
Fait.
