### ISSUE TITLE
Nouvelle adhésion - Mail désactivé - Pas de paiement - Inscription déjà validée

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#2]
* Nouvelle session (chrome incognito)
* Nouvelle adhésion
* Je complète le formulaire et je le soumets
* SOUCI : Affichage "La fonction mail() a été désactivée" (impossible de valider le mail reçu)
* Je vais dans mon profil (JTest_user / Joomla_test_User
 et 
     - Je vois que mon inscription est déjà validée pour une durée d'une année ![Uploading 2018-02-26_18h09_24.png…](Adhésion déjà active)
     - Je peux déjà télécharger une facture

et cela alors que je n'ai pas eu d'écran de paiement.

**Comment by sebastienlapoux** [comment]
comme expliqué

**Comment by cavo789** [comment]
Pardon ? Qu'as-tu expliqué ? 

Je mentionne plusieurs soucis : le PDF est déjà présent alors que je n'ai rien payé, l'adhésion est déjà active pour une année, ... rien à voir avec le mail non reçu...
