### ISSUE TITLE
Annuaire Pro - Utilisation d'un filtre - Message "Il n'y a pas de résultat"

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#20]
Perso, je trouve l'affichage un peu trop "big"; c'est juste un goût personnel.
J'aurai plutôt vu un discret "Aucun résultat retrouvé" dans la partie contenu.

![2018-02-26_20h26_22](https://user-images.githubusercontent.com/355999/36690697-6d1236f8-1b33-11e8-9614-4a705bd8fb7f.png)

**Comment by sebastienlapoux** [comment]
Merci. Utilise le message Joomla comme les autres recherche. Ouvrir une issue pour demande d'amélioration si besoin.
