### ISSUE TITLE
Contenu - Page Évènements

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#21]
https://dev-www.joomla.fr/evenements

"coeur" => "cœur"
"événements" => "évènements" (puisqu'il faut être cohérent avec le titre de la page; une seule graphie)
"Retrouvez sur cette page, le calendrier" => virgule inutile
"Vous pouvez également proposez vos dates " => "proposer" infinitif
"proposez vos dates pour le partager " => les partager (puisque "vos dates")

**Comment by sebastienlapoux** [comment]
Texte changé. Tu peux aussi le faire via l'icone d'édition qui apparait au survol : 
![image](https://user-images.githubusercontent.com/13470265/36792277-7243c8ae-1c9a-11e8-8c5a-e91c5b5ba36f.png)
