### ISSUE TITLE
Anciens Évènements

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#22]
https://dev-www.joomla.fr/evenements/archives

"ANCIENS ÉVENEMENTS" ==> ANCIENS ÉVÈNEMENTS (puisque c'est bien cette orthographe qui est utilisée sur https://dev-www.joomla.fr/evenements)
"Retrouvez ici le calendrier des anciens événements " => évènements

**Comment by sebastienlapoux** [comment]
fixé
