### ISSUE TITLE
Laisser un commentaire - Faut-il être adhérent ? 

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#23]
Juste pour être sûr : faut-il être un adhérent pour poster un commentaire (plus globalement pour avoir un compte sur le portail) ? 

>https://dev-www.joomla.fr/evenements/jugw-rencontre-de-la-rentree-septembre-2017

"LAISSER UN COMMENTAIRE
La soumission de commentaires est réservée aux adhérents de l'AFUJ. Merci de vous connecter pour soumettre un commentaire."

Si je ne suis pas adhérent, si je vois un évènement organisé par un JUG, je ne peux donc pas laisser un commentaire "Wow, cool, j'aimerai bien y prendre part", "Auriez-vous une brochure, une présentation, ..." bref : je suis "visiteur" et j'aimerai entrer en contact avec l'organisateur.

On ne peut pas ?

**Comment by sebastienlapoux** [comment]
Oui, commentaire que pour adhérent. A été décidé ainsi.
Ré-ouvrir débat au niveau CA si besoin.

**Comment by cavo789** [comment]
Je pense que c'est une grosse erreur.

Cela veut dire que le néophyte qui arrive et qui voit "Oh cool, un évènement près de chez moi" et souhaite intervenir pour demander quelque chose ... devrait passer à la caisse ?

C'est une erreur de procéder ainsi IMHO
