### ISSUE TITLE
Page Évènements - deux URLs pour quasi le même contenu

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#25]
Il y a https://dev-www.joomla.fr/evenements et https://dev-www.joomla.fr/la-communaute/evenements qui, au final, présentent la même chose non ?

**Comment by sebastienlapoux** [comment]
Non. Chaque catégorie : Joomla, Association et Communauté ont leur propre contenu, si cela bien sure est respecté. Un tour a été fait avant mise en prod.
A discuter au CA si besoin.

**Comment by cavo789** [comment]
C'est quoi la différence entre la page évènements et la page la-communauté/évènements ? 
Je suis un quidam : aucune. Je ne comprends pas la différence.

Je suis Christophe et je n'en vois pas non plus l'intérêt. Pour moi, c'est deux fois la même chose.
