### ISSUE TITLE
COMMUNAUTÉ - ÉVÈNEMENTS

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#26]
En lien avec #25 

Si cette page "COMMUNAUTÉ - ÉVÈNEMENTS" est bien utile :

"prochains événements " => évènements
"liés à la communauté francophone: " => en lien avec la communauté francophone (ou mieux mais je n'ai pas trop d'idée, juste que "liés" c'est pas trop ça"
"Joomapéro, Joomsessions, " => Joomapéro n'existe plus; on parle de JUG meeting (réunions JUG) et Joomsessions est un mot inexistant.

>mais aussi à l'univers de l'open source et du web...

On va publier des évènements non Joomla sur joomla.fr ? La page https://dev-www.joomla.fr/evenements n'évoque pas cette possibilité ni la page de soumission (qui ne propose pas de charte "que peut-on proposer?")

**Comment by sebastienlapoux** [comment]
texte modifié. Merci de reporter à l'équipe rédaction le point de la charte "que peut-on proposer".
Je cloture ici qui est destiné d'une manière générale aux fonctionnalités.
