### ISSUE TITLE
Création d'un utilisateur, introduction d'une adresse email sans nom de domaine

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#27]
Tentative de création d'un compte où j'ai mis n'importe quoi mais surtout pas de nom de domaine pour l'email : 

![2018-02-26_20h47_23](https://user-images.githubusercontent.com/355999/36691680-45814734-1b36-11e8-9487-de4bc66b8a4f.png)

Sanction : 

![2018-02-26_20h46_26](https://user-images.githubusercontent.com/355999/36691620-2811cb4c-1b36-11e8-8be1-43a2d10e223c.png)

(au lieu d'un "Cette adresse email n'est pas correctement complétée".)

**Comment by lionelratel** [comment]
Corrigé.  
Les 3 validations sont opérationnelles :  
- Required  
- Availability  
- Email valide
