### ISSUE TITLE
[Question] Modération des évènements ? 

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#29]
Pense-bête / question : est-il prévu de modérer les évènements avant publication ? 

Je n'ai jamais vu cela jusqu'à aujourd'hui sur le portail càd quelqu'un complète le formulaire => est-ce que la proposition est acceptée immédiatement ou est-elle en attente de modération (=> qui reçoit le mail de demande d'approbation?)

**Comment by sebastienlapoux** [comment]
Non pas de modération. Seul les adhérents peuvent soumettre et la publication est publiée de suite.
Modération à postériori basé sur la responsabilité de nos adhérents.

**Comment by cavo789** [comment]
Si personne ne reçoit de mails, une publication risque d'être là des semaines sans que quelqu'un s'en rende compte... Je ne crois pas que ce soit une bonne approche.
