### ISSUE TITLE
Profil - Chargement avatar - Affichage

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#3]
* Edition de mon profil (JTest_User)
* Ajout prénom, code postal, ... Cela fonctionne
* Je clique sur l'onglet Avatar et j'en charge une (du film du même nom; sauvée sur mon disque dur).
* Je clique sur enregistrer.
* L'onglet "Compte utilisateur" apparaît en rouge (une erreur???), je vais voir, non rien : tout semble correct.
* je clique sur enregistrer sans même modifier quoi que ce soit, cela semble fonctionner.
* Je vais à nouveau sur Avarar et l'aperçu ne donne rien (je suis supposé voir l'avatar)

![2018-02-26_18h19_50](https://user-images.githubusercontent.com/355999/36684779-b1494eb8-1b21-11e8-8e04-9f008f7d779d.png)

* je sauve à nouveau et je reviens dans la page de profil : l'avatar est présent.

![2018-02-26_18h21_04](https://user-images.githubusercontent.com/355999/36684811-cfe18372-1b21-11e8-833c-567bbf11aa02.png)

**Comment by sebastienlapoux** [comment]
@cavo789 , merci de tester à nouveau. Etait possiblement du à la confirmation du mot de passe.

**Comment by lionelratel** [comment]
Bonjour,  
le champ était juste paramétré pour afficher le nom du fichier "Apercu => avatar.jpg"  
Je l'ai passé en affichage de la miniature.
