### ISSUE TITLE
Contrôle sur la date incorrect

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#30]
https://dev-www.joomla.fr/mes-evenements/form/seb_event

Le 1er mars est bien postérieur au 28 février et pourtant ...

![2018-02-26_20h57_22](https://user-images.githubusercontent.com/355999/36692172-ad5f9c60-1b37-11e8-8abf-2a42a2de5d2a.png)

**Comment by sebastienheraud** [comment]
Bonsoir,

2 solutions rapides (sans développement), au choix : 

- changer le format de date affichée en International Y-m-d H:i:s et laisser la validation de comparaison des dates, qui fonctionnera correctement)
- retirer la validation de comparaison des dates, et donc permettre toute date de fin (mais en même temps pas d'impact fonctionnel/problématique réel)

Dans les 2 cas on garde la validation de format de date.
Dans l'attente de vos retours.

Cordialement,

**Comment by sebastienlapoux** [comment]
Merci @sebastienheraud .
Retirer la validation.

**Comment by cavo789** [comment]
Est-ce que https://github.com/moment/moment pourrait aider ?

**Comment by sebastienheraud** [comment]
@sebastienlapoux validation enlevée.
@cavo789 merci pour le lien.

Cordialement
