### ISSUE TITLE
URL invariable dans la page des contacts

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#32]
https://dev-www.joomla.fr/contact

Imaginons que je souhaite communiquer le lien par email / sur le forum à quelqu'un

Je vais sur l'un des quatre onglets, l'URL ne change pas; je sélectionne un "objet" depuis la liste déroulante, le contenu s'adapte mais pas l'URL.

![2018-02-26_21h08_24](https://user-images.githubusercontent.com/355999/36692750-3aeae03e-1b39-11e8-9375-c2146b1b325b.png)

**Comment by lionelratel** [comment]
Bonjour,   
dans le gestionnaire de contenus uniques : https://www.joomla.fr/admin/contenu/contenus-uniques  
nous avons ajouter l'URL disponible pour chacune des aides :  

<img width="500" alt="capture d ecran 2018-03-16 a 17 11 16" src="https://user-images.githubusercontent.com/9533292/37531918-df11ca26-293d-11e8-84f5-5b8e1d63f692.png">  

Avec ces urls, le bon onglet est ouvert et le select est rempli.  

Cordialement.

**Comment by sebastienlapoux** [comment]
Bonjour @cavo789 ,

Merci pour ton retour.

Bien cordialement.

**Comment by sebastienlapoux** [comment]
Bonjour @cavo789 

Pour ouvrir les onglets : 

- https://www.joomla.fr/contact?#Aide__Assistance
- https://www.joomla.fr/contact?#Association
- https://www.joomla.fr/contact?#JUG
- https://www.joomla.fr/contact?#Partenariat

Pour ouvrir une option du select, exemple
https://www.joomla.fr/contact?c=279#Aide__Assistance

Bien cordialement.
