### ISSUE TITLE
Contenu - Actualités

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#33]
https://dev-www.joomla.fr/actualites

`Toutes les actualités de Joomla! en mode francophone ` => toutes les actualités francophones de Joomla! (virer le "en mode")

Il y a deux puces : 
- les annonces officielles : les nouvelles versions, les correctifs et les mises à jour, 
- les infos en provenance de la communauté : les compte-rendus de l'AFUJ, des Joomla: User Group, des événements du monde du logiciel libre, 

mais vu le centrage, ce n'est pas très lisible qu'il s'agisse de puces (qui, si ce sont des puces, devraient être aligné à gauche).

Peut-être remplacer par 

les annonces officielles (les nouvelles versions, les correctifs et les mises à jour) et
les infos en provenance de la communauté (les compte-rendus de l'AFUJ, des Joomla: User Group, des événements du monde du logiciel libre)

Retirer le ":" dans `des Joomla: User Group`

**Comment by cavo789** [comment]
"N'hésitez pas à proposez vos actualités en lien avec Joomla!" : mettre le lien aussi ici (comme on le retrouve plus bas) : https://dev-www.joomla.fr/actualites/proposer-une-actualite

**Comment by sebastienlapoux** [comment]
Merci @cavo789 .
Complété.
