### ISSUE TITLE
Contenu - Suggestion - Page de description du CA

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#35]
Je n'ai pas trouvé une page qui présente le CA : qui, depuis quand, jusqu'à quand et quel est le rôle (Président, ...).

**Comment by sebastienlapoux** [comment]
Le CA est disponible ici https://www.joomla.fr/association/membres?seb_user_keywords=&seb_user_membre_2=1&seb_member_ordering=user_last_name%3Aasc&search=seb_users&task=search
Sur la fiche utilisateur est affiché notamment si membre du CA https://www.joomla.fr/association/membres/thierry-broussegoutte . En cours pour la position (trésorier, président...) qui est déjà géré au niveau des profils mais affiché sur la fiche utilisateur.
Ensuite, une autre page (comme status ou réglement) pour d'autres infos sur le CA ou sur l'histoire de l'AFUJ, voir avec équipe rédactionnelle.
