### ISSUE TITLE
Recherche en POST versus GET 

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#36]
Est-il possible de passer quelques paramètres en POST ? 

Une recherche de, p.ex. "conseil d'administration" donne https://dev-www.joomla.fr/rechercher?seb_search_general_keywords=conseil+d%27administration&boxchecked=0&search=seb_search_general&task=search

`boxchecked=0&search=seb_search_general&task=search` est peu utile dans l'URL pour l'utilisateur final.

**Comment by sebastienlapoux** [comment]
https://www.joomla.fr/rechercher?seb_search_keywords_module=&search=seb_search_general&task=search

boxhcecked a été supprimé.

Les autres sont necessaires pour l'instant.
D'autres améliorations sur ces points arriveront sur 2018.
