### ISSUE TITLE
Mail - Votre compte sur Joomla.fr --> Spam

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#37]
Christian Bardin m'informe qu'il a reçu le mail immédiatement dans sa boîte mail Spam.

Personnellement, je l'ai bien reçu dans ma boîte de réception (Yahoo)

```
Bonjour,

Veuillez trouver vos informations de connexion sur le nouveau portail Joomla.fr
Identifiant : XXXXXXXXXX
Mot de passe : XXXXXXXXXXXX
Le site est momentanément hors ligne, et sera disponible d'ici quelques heures.

Cordialement.

L'AFUJ
www.joomla.fr
```

**Comment by YGomiero** [comment]
Hello,

idem car non sécurisé : http://prntscr.com/ikx0bj

Ce que je conseille à mes clients :

1. Etendre le certificat SSL aux emails en plus du spf/dkim/dmarc. 

2. Avertir du problème et changer son mot de passe rapidement. Aux administrateur du site de forcer le changement à la première connexion (il y a des solutions gratuites comme https://extensions.joomla.org/extension/force-password-change/ ).

Eviter à l'avenir de transmettre tout mot de passe ou données sensibles par email. Peu importe le niveau de sécurité. C'est à l'utilisateur à réinitialiser ou générer son mot de passe via un token créé de façon temporaire. 

Merci ;)

**Comment by sebastienlapoux** [comment]
Merci @cavo789 et @YGomiero .

Yann, pas obligatoirement du au chiffrement de l'email peut être aussi selon les règles du destinataire. Mais on va essayer de regarder ce point.

**Comment by sebastienlapoux** [comment]
@YGomiero , réponse de Romain : 
Je ne vois pas comment il est possible de chiffrer un mail à destination d’utilisateurs lambda.
Le SPF et DKIM sont déjà en place pour les sites joomla.fr.
Le DMARC ne l’est pas car cela demande à ce que tous les e-mails partent uniquement du serveur faisant le SPF et DKIM du domaine en question.

Yann, d'ou vient le screenshot que tu as posté s'il te plait ?

**Comment by sebastienlapoux** [comment]
Merci @YGomiero .

Situation actuelle déjà bien correcte. Pas d'optimisation supplémentaire en l'état.

Je clos.
