### ISSUE TITLE
Impossible de modifier un événement dont je suis l'auteur

### ISSUE THREAD

**Issue by com3elles** [AFUJ/joomla.fr#39]
https://www.joomla.fr/evenements/joomladay-fr-2018
J'ai créé cet événement lors des tests du portail il y a quelques semaines.
Je n'y ai plus les droits d'édition visiblement alors que j'arrive à modifier les articles que j'avais créé pour mon JUG

**Comment by sebastienlapoux** [comment]
Bonjour @com3elles ,

Ton compte fait partie des 3 cas ou il y avait 2 comptes pour la même personne. Peut être est ce du au fait que nous avons "mergé" tes comptes.
Quand tu es sur https://www.joomla.fr/evenements/joomladay-fr-2018 en mode identifié, vois-tu l'icone d'édition ?
Quand tu vas sur le gestionnaire d'évènement dans le menu admin, vois-tu ton évènement, peux-tu cliquer sur éditer ?
Merci de préciser si message d'erreur.

Bien cordialement.

**Comment by com3elles** [comment]
Bonjour Sébastien.
C'est bien le problème, connectée, je ne vois pas cette icone d'édition sur cet événement alors que sur d'autres contenus que j'avais créé (actualités) à la même période j'ai bien cette icone. 
J'avais bien vérifié dans mon menu "mes événements" et celui-ci apparait bien en même temps qu'un autre que j'ai créé hier https://www.joomla.fr/evenements/apero-special-seo-jug-virtuel.
Je vois par contre que même ce dernier n'est pas modifiable par moi. D'où la piste des droits ...
Pas de message d'erreur.

**Comment by sebastienlapoux** [comment]
Merci @com3elles .
Quand tu vas sur le gestionnaire d'évènement dans le menu admin, vois-tu ton évènement, peux-tu cliquer sur éditer ?

**Comment by com3elles** [comment]
Non, nulle part. 
Les 2 événements suivants ont été créés par moi et je ne vois pas l'icone d'édition
![image](https://user-images.githubusercontent.com/4996091/36790358-d05008aa-1c94-11e8-80ef-67bc2f41bf6d.png)
A contrario, on voit sur cette actu que j'ai bien cette icone : 
![image](https://user-images.githubusercontent.com/4996091/36790420-0e0a437c-1c95-11e8-9ee4-2d3a66e9405e.png)

**Comment by agerix** [comment]
![2018-02-28_15h33_38](https://user-images.githubusercontent.com/3830166/36793117-cf740320-1c9c-11e8-9a32-c481dda09f29.png)

Je confirme la modification est possible sur les événements

**Comment by lionelratel** [comment]
La gestion des accès / permissions vient d'être reprise sur les type de contenus :  
- Actualité  
- Évènement  
- JUG  
- Professionel  

Tout est normalement fonctionnel.

**Comment by com3elles** [comment]
Je confirme ça fonctionne. Merci
