### ISSUE TITLE
pas de og:image sur page d'accueil (embêtant pour communication autour de joomla.fr)

### ISSUE THREAD

**Issue by woluweb** [AFUJ/joomla.fr#41]
Bonjour et merci à l'équipe !

- sur les pages internes telles que l'appel à conférenciers, il y a bien un <meta property="og:image"
- par contre, sur la page d'accueil, rien.
Du coup, les partages sur les réseaux sociaux affichent juste l'url du site, sans Image.
Y'a pas mort d'homme, mais ce serait sympa de corriger cela avant la communication urbi et orbi sur le nouveau portail

**Comment by lionelratel** [comment]
Bonjour,  
les meta Open Graph sont en place sur la page d'accueil.  
Image utilisée et modifiable depuis le gestionnaire de media en backend : https://www.joomla.fr/images/decouvrez-cms-joomla.jpg  

Cordialement.

**Comment by woluweb** [comment]
Merci Lionel.
Génial, ça marche :).
