### ISSUE TITLE
Impossible de créer son JUG

### ISSUE THREAD

**Issue by agerix** [AFUJ/joomla.fr#42]
Salut,

En l'état il n'est pas possible de créer son JUG online et donc de proposer son événement

**Comment by cavo789** [comment]
Je viens de regarder, la création d'un JUG serait uniquement disponible pour des admins; est-ce possible de confirmer ? 

![2018-02-28_12h30_23](https://user-images.githubusercontent.com/355999/36785724-1c8dc68c-1c84-11e8-8696-6260954247e3.png)

Et si c'est le cas, comment un non-admin (Eric, Yann, ...) peut-il gérer sa propre page ?

**Comment by sebastienlapoux** [comment]
Bonjour @agerix ,

Comme mentionné sur https://www.joomla.fr/la-communaute/joomla-user-groups il faut nous contacter, ce que je considère comme fait avec ton issue sur Git.

Le principe : nous contacter afin que manuellement nous assignons (après vérification que la demande émane de l'une des personnes officiellement responsable d'une JUG https://community.joomla.org/user-groups/europe/france/975-joomla-user-group-bordeaux.html) ton compte utilisateur au groupe d'utilisateur JUG afin que tu puisse gérer ta JUG dans ton menu utilisateur : 
![image](https://user-images.githubusercontent.com/13470265/36786038-3aff272c-1c85-11e8-9fd4-84d26bcb437f.png)

Ton compte a été assigné au groupe JUG, tu peux maintenant créer ta fiche JUG Bordeaux.

Note : actuellement un seul propriétaire/auteur d'une fiche JUG, mais possibilité à tout adhérent de créer une actualité ou évènement dans une JUG

Bien cordialement.

**Comment by sebastienlapoux** [comment]
@cavo789 , le menu administration que tu mets en copie écran n'est accessible que pour les gestionnaires du site.

**Comment by cavo789** [comment]
La réponse à la question "Et si c'est le cas, comment un non-admin (Eric, Yann, ...) peut-il gérer sa propre page ?" est donc il faut que quelqu'un assigne l'utilisateur au groupe JUG.

**Comment by com3elles** [comment]
En lien avec ma demande d'amélioration (style bouton), si cette phrase est mieux mise en avant ça évitera ce type de question. Je suis moi-même passée à côté quand Eric m'a demandé

**Comment by agerix** [comment]
Bonjour @sebastienlapoux 

Merci beaucoup pour ton intervention, j'ai pu créer notre JUG bordelais. Par contre (dis moi si je dois créer une nouvelle issue ici) la modification du JUG n'est pas possible une fois celui-ci publié. Je m'en suis rendu compte en voyant que le logo n'était pas dans la bonne dimension.
Merci encore de vos réponses,
Bonne journée

**Comment by sebastienlapoux** [comment]
Merci @agerix .

On regarde pourquoi.

Note : j'ai redimensionné le logo avec la fonction de recadrage que tu as sur la fiche JUG (quand tu y accède)

**Comment by lionelratel** [comment]
Bonjour @agerix ,  
la gestion des accès et permissions a été corrigé sur les JUG.  
L'édition par un gestionnaire de JUG doit être possible maintenant.  
Cordialement.

**Comment by agerix** [comment]
Bonjour @lionelratel 

Je confirme, merci !
