### ISSUE TITLE
Cet utilisateur n'existe pas - mon propre compte

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#44]
Ce matin vers 11h00 je tente de m'identifier sur le frontend, je reçois un "Cet utilisateur n'existe pas" pour mon utilisateur christophe.avonture@xxxx.fr.

Le mot de passe provient de mon lastpass (et donc est supposé correct car hier soir 22h00 c'était OK).

Marche pas, "Cet utilisateur n'existe pas"

Je tente sur le site dev-xxxx et le login / mot de passe fonctionne (même login / même pwd).

Je retente une heure après, cela passe fonctionne.

J'ai été bloqué immédiatement, ce n'est donc pas un blocage du compte parce trop d'essais (une fois encore, le password vient de Lastpass; je ne peux pas me tromper en l'encodant; il est proposé par défaut)

**Comment by cavo789** [comment]
A nouveau bloqué

![2018-02-28_13h07_54](https://user-images.githubusercontent.com/355999/36786928-7cc25410-1c88-11e8-9144-84258d1ac729.png)

**Comment by lionelratel** [comment]
D'après ta copie d'écran, l'identifiant saisie est "christophe.avonture".
Or la connection se fait avec l'email. Dans ton cas "christophe.avonture@joomla.fr"

**Comment by cavo789** [comment]
Correct, cela fonctionne ainsi;
