### ISSUE TITLE
Style bouton pour les contenus

### ISSUE THREAD

**Issue by com3elles** [AFUJ/joomla.fr#45]
Je n'ai pas trouvé dans l'éditeur ni dans l'article exemple proposé pour l'aide la possibilité de créer un lien de type "Bouton" un peu visible.
J'ai rajouté la classe "btn" via le code source mais le texte restant bleu sur fond bleu ça n'est pas génial.
Par exemple dans https://www.joomla.fr/actualites/enquete-vendre-ou-non-joomla le lien pour accéder à l'enquète est peu visible et le serait plus avec un style bouton.
C'est encore plus criant sur https://www.joomla.fr/actualites/appel-a-conferencier-joomladay-2018

**Comment by sebastienlapoux** [comment]
@com3elles , merci.

Oui. Ai fait une modif mais imparfait https://www.joomla.fr/actualites/enquete-vendre-ou-non-joomla

Nous allons ajouter dans l'article exemple une présentation de lien plus visible et également gérer les liens dans les "containers" de l'éditeur.

**Comment by com3elles** [comment]
Yes, c'est une bonne idée ! Merci

**Comment by sebastienlapoux** [comment]
Bonjour @com3elles ,

Voir article exemple, de joli boutons à dispo facilement : 

![image](https://user-images.githubusercontent.com/13470265/36843760-3464a268-1d50-11e8-9ccd-30ba265a6901.png)
