### ISSUE TITLE
Adhésion pour quelqu'un qui n'a pas de nom

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#46]
![2018-02-28_12h44_54](https://user-images.githubusercontent.com/355999/36786043-3da6901e-1c85-11e8-9516-57d8d3b6e373.png)

Si on demande la facture, c'est une adhésion à 1 euro pour Alexandre Lapoux.

Un test a supprimer donc.

**Comment by sebastienheraud** [comment]
Bonjour,
Nous avons passé son état en "Annulé", ce qui permet de la conserver pour accéder à la facture, car un paiement "réel" a été fait.
Cordialement
