### ISSUE TITLE
[info] Adhésion - date début + un an <> date de fin

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#47]
Pour certains la date de fin est date début + un an (ce qui est conforme à la durée de l'adhésion). Pour d'autres, p.ex. Samuel Huet,  c'est 16 mois.

![2018-02-28_12h48_14](https://user-images.githubusercontent.com/355999/36786163-a80cb5f0-1c85-11e8-8136-e0cfd947eed1.png)

**Comment by cavo789** [comment]
**Vérification faite sur CBSubs pour Samuel : c'est correct, cela semble donc indiquer que son précédent abonnement avait été renouvellé plusieurs mois avant son terme, il y avait donc un reliqua qui a été repris par CBSubs et donc une durée supérieure à 12 mois**

(je poste pour documentation)

**Comment by sebastienlapoux** [comment]
@cavo789 , j'ai supprimé ta copie écran. Merci de ne pas rendre publique des informations personnelles de nos adhérents.
