### ISSUE TITLE
Prise de contact - envoi depuis no-reply

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#48]
Les demandes de contact; avec le précédent portail, utilisaient l'email de la personne.

Ainsi, après réception dans la mailbox @joomla.fr, on pouvait faire un "Reply" et l'email du destinataire était la personne.

Aujourd'hui, c'est "no-reply" et forcément, le mail me revient.

![2018-02-28_16h41_20](https://user-images.githubusercontent.com/355999/36796644-4bd61724-1ca6-11e8-9eae-4407cbb03c8c.png)

Est-ce possible de continuer à faire comme avant ? Parce qu'on se fera souvent avoir... 

Merci

**Comment by sebastienlapoux** [comment]
@cavo789 , merci. Nous ne pouvions plus le faire car l'email du from doit correspondre au nom de domaine du site (problématique réputation/authentification expéditeur). La solution est de passer par le paramètre reply name / reply to de l'entête d'un email. Nous venons la semaine dernière de gérer cela pour le champ email.
Nous allons donc le mettre en place.
En cours.

**Comment by lionelratel** [comment]
Le "Reply To" et "Reply To Name" est en place sur le mail aux administrateurs pour les deux formulaires de contact "Site" et "Professionel"

**Comment by cavo789** [comment]
Je clôture car en effet, la modification faite par @lionelratel a permis d'apporter une solution.
