### ISSUE TITLE
www.afuj.fr redirige vers www.joomla.fr/afuj/ qui donne une 404

### ISSUE THREAD

**Issue by woluweb** [AFUJ/joomla.fr#49]

**Comment by sebastienlapoux** [comment]
merci @woluweb .

Il y a un gestionnaire de redirection à dispo dans lequel ont été créé toutes les entrées pour les anciennes URL (qui ont scannée).

Je viens de rendre effectif celle pour /afuj
![image](https://user-images.githubusercontent.com/13470265/36845214-1a08213c-1d56-11e8-9d9a-79cdd6e28c2d.png)

Note : en cours pour fixer le fait que un slash soit présent à la fin ou non (fonctionne pas pour l'instant avec /afuj/).

Il y a des milliers de redirections à traiter. Il faudrait du monde dessus.

Bien cordialement.

**Comment by woluweb** [comment]
Merci @sebastienlapoux !
Sûr qu'il y aura d'autres redirections à traiter, mais celle-là était prioritaire :)
Merci pour la réactivité ;)

**Comment by sebastienlapoux** [comment]
Merci @woluweb .
Je ne suis pas sure qu'il fasse sens d'utiliser le lien afuj.fr qui n'existe plus. Pourquoi ne pas pointer directement sur https://www.joomla.fr/association/adherer ? Ou alors il faudrait une page https://www.joomla.fr/association/afuj décrivant notre association (qui est l'afuj) ?

**Comment by lionelratel** [comment]
Bonjour,  
toutes les urls inclues dans le gestionnaire de redirections sont désormais prises en compte aussi bien sans le "/" qu'avec le "/".  
Donc pas besoin de dupliquer l'Url dans le gestionnaire.

**Comment by woluweb** [comment]
Okidoki. Hyperlien corrigé pour ne plus utiliser afuj.fr

**Comment by sebastienlapoux** [comment]
Merci à vous 2, je clos.
