### ISSUE TITLE
Generator - Joomla

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#53]
Est-il possible de réinitialiser le `generator` sur les pages du portail ? 

Merci

**Comment by sebastienlapoux** [comment]
Bonjour @cavo789 ,

Merci. 

`<meta name="generator" content="Joomla!, SEBLOD" />`
Quand SEBLOD est utilisé, le meta generator est changé avec celui-ci, c'est le comportement par défaut.
Nous allons le supprimer.

Bien cordialement.

**Comment by lionelratel** [comment]
Bonjour,  
Generator réinitialisé.  

Cordialement.

**Comment by sebastienheraud** [comment]
Bonjour,
Pour info : le generator provenait du template du site.
Cordialement
