### ISSUE TITLE
Qui s'occupe de la page des anciennes versions ? 

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#59]
La page https://www.joomla.fr/joomla/telecharger-joomla/anciennes-versions s'arrête à J3.7.2

Qui fait quoi et comment (mode d'emploi) ?

**Comment by Opware2000** [comment]
Je suis entrain de mettre à jour les anciennes version.

**Comment by sebastienlapoux** [comment]
Merci @Opware2000 !
