### ISSUE TITLE
Titre illisible - "IDENTIFIANT OUBLIÉ ?"

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#6]
Le texte "IDENTIFIANT OUBLIÉ ?" est écrit en blanc, pas très lisible

![2018-02-26_18h34_52](https://user-images.githubusercontent.com/355999/36685495-caad0de8-1b23-11e8-90e1-92c0f6c29050.png)

**Comment by sebastienlapoux** [comment]
@cavo789 en cours

**Comment by lionelratel** [comment]
Bonjour,  
c'est corrigé.  

Cordialement.
