### ISSUE TITLE
Problème sélecteur de date

### ISSUE THREAD

**Issue by Opware2000** [AFUJ/joomla.fr#60]
Problème d'affichage du sélecteur de date 
- coupé en bas : [http://prntscr.com/iqqt6p](http://prntscr.com/iqqt6p)
- coupé en haut : [http://prntscr.com/iqqu90](http://prntscr.com/iqqu90)
sur la même page (nouvelle version de Joomla)

**Comment by sebastienlapoux** [comment]
Merci @Opware2000 ! 
Oui en effet. Tu peux toujours saisir manuellement dans le champ texte la bonne valeur, le temps de régler le problème.

Note : tu peux copier coller tes screenshots directement dans l'éditeur de Github

**Comment by Opware2000** [comment]
J’ai fais comme ça, en rentrant manuellement la date. Mais c’était pour signaler. 
Bonne soirée. 

Envoyé de mon iPhone

**Comment by lionelratel** [comment]
Bonjour @Opware2000 ,  
problème résolu.  

Cordialement.

**Comment by Opware2000** [comment]
Merci beaucoup
