### ISSUE TITLE
Problème article sauvé mais non affiché dans Mes actualités

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#63]
Dons son espace "Mes actualités", si on crée un article en lui affectant une **date de publication qui n'est pas encore atteinte** ... alors lorsque l'on clique sur "Enregistrer & Fermer", on ne retrouve plus l'article ?!
(la 1ere fois ca fait un peu flipper !!!)

Il faut utiliser le bouton "Page précédente" du navigateur pour retrouver son article (qui a bien été enregistré).
Et si on change la date de début de publication et que l'on affecte une date passée, alors quand on enregistre, on retrouve bien l'article dans "Mes actualités".

- Pouvez vous corriger pour qu'un auteur puisse voir **tous** ses articles ... même si la date de publication n'est pas encore atteinte ?
Merci

**Comment by lionelratel** [comment]
Bonjour @garstud,  
c'est corrigé.

Cordialement.
