### ISSUE TITLE
Le lien vers le forum depuis joomla.fr est en nofollow oups.

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#65]
Est-il possible de mettre les liens *.joomla.fr (comme le forum) en dofollow ?

Le référencement du forum est devenu catastrophique; avec l'aide de Yann j'en cherche la raison (pas encore trouvée) mais, sur le portail, le lien vers le forum est en nofollow ce qui ne devrait pas être le cas pour nos sites.

![noindex](https://user-images.githubusercontent.com/355999/37570236-b5df253e-2aed-11e8-8602-5987c6082571.png)

Merci

**Comment by cavo789** [comment]
Bonjour

Par curiosité, je repassais ici et, très prochainement cela fera un an que j'avais posté plusieurs points qui n'ont pas évolués.

**Comment by agerix** [comment]
J'ai regardé les paramètres du module et il n'y a aucun paramètres qui qualifie le lien fait. Il n'y a que @sebastienlapoux ou quelqu'un de son équipe qui pourra te répondre.

**Comment by lionelratel** [comment]
Bonjour,  
Ajout d'un champ pour choisir le "Nofollow" => Oui / Non  

<img width="725" alt="Capture d’écran 2019-04-18 à 12 10 02" src="https://user-images.githubusercontent.com/9533292/56354012-0ddb9980-61d3-11e9-9fd4-e0f13c917b71.png">

Cordialement.

**Comment by sebastienlapoux** [comment]
Merci @lionelratel .

Ok, je comprends mieux...

Ok pour les liens des boites ci-dessous (toute passée en nofollow à non)
![image](https://user-images.githubusercontent.com/13470265/56356051-197d8f00-61d8-11e9-8edc-f92a94372fa9.png)
Mais puisque forcément des liens vers le forum, pas vraiment utile de choisir, mais ok ainsi.

De mon côté, je parlais d'avantage de la boite 
![image](https://user-images.githubusercontent.com/13470265/56356164-534e9580-61d8-11e9-8688-ab45ea2bd49b.png)
@lionelratel Merci d'ajouter également le champ nofollow dans ce type de contenu "lien".

**Comment by lionelratel** [comment]
Champ ajouter sur les type de contenu Lien.
Différentes listes traitées.

**Comment by sebastienlapoux** [comment]
Merci @lionelratel , impec !

**Comment by agerix** [comment]
Merci à tous les deux ;)
