### ISSUE TITLE
La création d'événement depuis le Front ne marche pas !?

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#66]
Bonjour,
Je viens de tenter, par 2 fois, de créer un event JApero pour mon JUG Provence , sans résultat !

A chaque enregistrement, j'ai un msg vert disant "_Enregistrement effectué avec succès_", mais après, plus rien !?
L'event n'est pas publié et je ne le retrouve pas dans mes events !
c'est assez bloquant :( 

Pourtant il y a bien des events affichés sur le site, donc est ce que cela veut dire qu'en admin, la création d'event fonctionne, mais pas en front ?

**Comment by lionelratel** [comment]
Bonjour @garstud,   
merci pour la remontée.  
il y avait une mauvaise restriction sur le champ "State" pour les "Gestionnaire de contenu" ce qui mettait le state "11" aux évènements, donc plus visible nulle part (Back/Front).  
C'est corrigé.  

Cordialement.

**Comment by sebastienlapoux** [comment]
Merci @lionelratel !

bonjour @garstud , gestion du contenu exclusivement côté front, personne ne gère côté admin Joomla y compris les admin. Mais les admin ont du côté front des gestionnaires "globaux" qui donne accès à tous les contenus quelque soit l'auteur et avec des filtres de recherche supplémentaires.

Bien cordialement.

**Comment by garstud** [comment]
Merci @lionelratel et @sebastienlapoux  pour vos explications et pour la rapidité de traitement, c'est tout bon pour mon event ;)
