### ISSUE TITLE
Taille minimal des images contraignante !

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#67]
Bonjour,

Cela fait plusieurs fois que j'ai l'erreur :

> "Erreur L'image requiere une hauteur minimum de 214"

Or si je veux inserer un badge de certification ou une banniere allongé du JDay , ben ca passe pas :( 

Je suis obligé de modifier l'image pour ajouter une bande en haut et en bas de l'image ... pas terrible !

Vous serez-t-il possible de reduire la **limite de hauteur des images à 91 pixels** ?
Ce qui correspond a la hauteur des bannieres horizontale du JDay.
Merci pour votre retour.

**Comment by garstud** [comment]
un avis ou retour sur ce probleme ?

**Comment by sebastienlapoux** [comment]
Salut @garstud ,

Ok pour la hauteur, merci de tester.

Marc, merci à chaque fois de retailler l'image pour les 2 miniatures :  
![image](https://user-images.githubusercontent.com/13470265/39710576-751308c0-521d-11e8-9c45-889421a84ec9.png)

Bien cordialement.

**Comment by garstud** [comment]
Ok pour moi, ca marche bien, et la limite a 265 x 90 pixels est plus adaptée, merci  @sebastienlapoux
