### ISSUE TITLE
Publication auto ? mauvais timezone ?

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#68]
Bonjour, 

La publication auto d'un article a une heure donnée ne marche pas !
Il est 13h24 et mon article avec un début de publication "29-03-2018 11:30:00" n'est pas en ligne !

- S'agit-il d'un probleme de timezone ?

A 13h30, mon article apparait bien, donc ca confirme le probleme de config de timezone de Joomla, non ?

**Comment by garstud** [comment]
Des nouvelles sur ce probleme ?
Ca semblait etre juste un soucis de paramétrage du Timezone, non ?

**Comment by sebastienlapoux** [comment]
Bonjour @garstud ,

Merci d'essayer à nouveau.

Bien cordialement.

**Comment by garstud** [comment]
@sebastienlapoux , je viens de tester sur l'article "CP Episode 2 : Comment gérer ses Champs Personnalisés ?"
La date de début de publication et de fin de publication marche bien avec le Timezone francais.
Cette issue est donc closed, Mais cela m'a permis de detecter un autre probleme en relation ...
Voir https://github.com/AFUJ/joomla.fr/issues/71
