### ISSUE TITLE
Annuaire des pros : 

### ISSUE THREAD

**Issue by com3elles** [AFUJ/joomla.fr#69]
Bonjour,
j'avais fait un test il y a quelques temps de création d'une fiche dans l'annuaire des pros. Ca n'avait pas fonctionné et j'avais mis ça sur le compte de mon adhésion inadaptée bien que le site m'affichait le contraire :  
![image](https://user-images.githubusercontent.com/4996091/38504995-7228e4e4-3c16-11e8-8a0d-3935a860ad3c.png)
J'ai renouvelé mon adhésion tout à l'heure en prenant le bon niveau d'adhésion cette fois (professionnel de Joomla)
J'ai bien eu accès au formulaire comme lors de mon dernier test, le site m'a renvoyé que c'était bien enregistré mais cependant ma fiche n'est disponible ni en front (pas sur l'annuaire ni dans mon menu perso) ni en back ... 

Y-a-t'il un temps de validation de l'adhésion avant de pouvoir créer sa fiche (dans ce cas ne pas donner accès au formulaire) ou est-ce un bug ?

**Comment by sebastienlapoux** [comment]
Bonjour @com3elles ,

Merci. Ton compte à des accès particuliers. On va vérifier selon tes accès.

Bien cordialement.

**Comment by com3elles** [comment]
Bonjour,
as-tu des nouvelles de mon "bug". Merci

**Comment by com3elles** [comment]
Bonjour,
pourriez-vous me tenir au courant : vous-êtes vous occupés de mon "cas" ???
@sebastienlapoux @lionelratel
