### ISSUE TITLE
[À réouvrir] Commander et/ou Adhérer

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#7]
Y-a-t'il une raison pour que ce soit Commander pour "Personne physique" ? il s'agit bien d'une adhésion pourtant.

![2018-02-26_18h36_39](https://user-images.githubusercontent.com/355999/36685577-04178400-1b24-11e8-96a1-268423dde44d.png)

**Comment by sebastienlapoux** [comment]
Merci @cavo789 .
Adhérer partout sur page de sélection de l'adhésion.

**Comment by cavo789** [comment]
Je suis en mode navigation privée; parfois je vois encore Commander et Adhérer.

Cela peut  être un phénomène de cache mais c'est bizarre car je suis en mode privé et je fais CTRL-F5.

![2018-02-26_20h20_55](https://user-images.githubusercontent.com/355999/36690421-8d885fee-1b32-11e8-95aa-9d7eb92fb908.png)

Parfois je vois Adhérer des deux côtés...

**Comment by cavo789** [comment]
J'ai toujours ce problème et cela sur le nouveau site; ce n'est donc pas un souci de cache.

Parfois j'ai Adhérer / Adhérer, parfois pas.

À réouvrir
![2018-02-27_21h23_29](https://user-images.githubusercontent.com/355999/36752868-ae1a4718-1c04-11e8-9196-7e74c874832e.png)

**Comment by sebastienlapoux** [comment]
Bonjour @cavo789 ,

Oui et j'ai dit une bêtise sur ma dernière réponse.

"Commander" signifie que tu as déjà appuyé sur le bouton "Adhérer" et que ton adhésion est dans le "panier". Dans ce cas, en allant sur la page de commande et en supprimant l'adhésion si tu reviens sur lapage d'adhésion le "Commander" sera repassé en "Adhésion".

Le site joomla.fr dispose derrière qu'un système de panier qui peut permettre d'ouvrir à d'autres types produits à la vente et le système permet d'acheter en même temps des adhésions ou des produits sans récurrence.

Bien cordialement.
