### ISSUE TITLE
Probleme acces pour modifier mon JUG ?

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#70]
J'avais créé le JUG Provence il y a qq temps.
J'ai voulu y retourner pour completer la fiche. Depuis mon compte, j'accède bien à "Mon JUG" :
https://www.joomla.fr/mon-j-u-g/jug-provence

Mais quand je clique sur le "crayon" pour modifier la fiche, j'ai une popup de htpasswd qui surgit :
![capture_2018-04-13_num01](https://user-images.githubusercontent.com/970021/38758720-a141fcd4-3f72-11e8-8ede-581abff771a4.png)
Elle bloque l'accès à la page suivante :
https://www.joomla.fr/admin/utilisateurs/j-u-g/form/seb_jug?id=10553&return=aHR0cHM6Ly93d3cuam9vbWxhLmZyL21vbi1qLXUtZy9qdWctcHJvdmVuY2U=

- Avez-vous des explications ?
- Y a t-il un problème a corriger ?
Merci pour votre aide.

**Comment by sebastienlapoux** [comment]
Salut @garstud ,

Merci.
Le lien devrait maintenant en référence à /mon-j-u-g/:  
![image](https://user-images.githubusercontent.com/13470265/39710104-25af3142-521c-11e8-8a52-1ff5e3c42724.png)

Merci pour ton retour.

Bien cordialement.

**Comment by garstud** [comment]
Hello,
Well, aucun changement :( 
C'est comme sur ta derniere capture, dès que je clique sur le bouton  "crayon" de mon JUG, ca renvoie vers une url www.joomla.fr/admin/utilisateurs/j-u-g/**form/seb_jug**?id=10553&return=aHR0cHM...
qui est protégée par un htpassword !

**Comment by sebastienlapoux** [comment]
Merci @garstud .

Que l'URL /admin soit protégée est normal.
Ce qui ne l'est pas c'est que tu vois un lien faisant référence à /admin et pas à /mon-j-u-g

Ok, tu n'étais pas dans le groupe JUG qui permet de pouvoir gérer et accéder à sa propre fiche, corrigé. Tu as pu la créer car tu étais dans le groupe gestionnaire de contenu, je t'ai supprimé de celui-ci car à priori pas utile, tu dois pouvoir faire les mêmes actions que tu faisais auparavant.

Merci pour ton retour.

**Comment by garstud** [comment]
Ok, merci @sebastienlapoux , c'est tout bon !
