### ISSUE TITLE
Erreur 404 lorsque j'edite un de mes articles

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#71]
Je me suis trompé et j'ai renseigné une date de fin de publication inférieur a aujourd'hui.
Je comprends que cela empeche de voir l'article sur le site ....
Mais si je sors de l'article en modification dans l'espace auteur, alors je ne peux plus y rentrer ! j'ai une erreur 404 !

- Pouvez vous corriger afin qu'un auteur **puisse editer tous ses articles**, y compris **ceux qui sont arrivés a la date de fin de publication** ?
Merci.

**Comment by garstud** [comment]
Urgent : Est-ce que vous pouvez vider le champ **date de fin de publication** de l'article CP Episode 2 : Comment gérer ses Champs Personnalisés ?"
... car du coup avec les tests sur le #68, cet article se retrouve hors ligne suite a ce présent bug !

**Comment by sebastienlapoux** [comment]
@garstud Fait https://www.joomla.fr/actualites/cp-episode-2-comment-gerer-ses-champs-personnalises

**Comment by garstud** [comment]
Ok merci @sebastienlapoux  ;) 

Je viens de me rendre compte que j'avais tout de meme acces en cliquant sur le crayon en bout de ligne a droite. Donc c'est bon, le bug n'en est pas un !
Mais comme j'ai eu le reflexe de cliquer sur le titre, le 404 m'a perdu !

D'ailleurs ca me fait pensé que contrairement aux articles dans Joomla, quand un article joomla.fr est dépublié les auteurs ne peuvent pas le consulter en ligne ... alors que dans Joomla com_content, quand tu navigues **en frontend sur un article dépublié, en tant qu'auteur tu y a acces normalement** !
(et ca aide bien les auteurs quand ils veulent verifier le rendu avant publication)
- est-ce que ce fonctionnement est possible avec Seblod ?
(ou un systeme de preview ?)

**Comment by sebastienlapoux** [comment]
Bonjour @garstud ,

Dans Joomla, les super user peuvent voir un article dépublié en front mais pas l'auteur de l'article. A moins que je ne sois pas au courant d'un changement récent sur le sujet.

Tu peux accéder à tous tes articles publiés ou pas dans ton gestionnaire d'article. Nous avons ajouté le champ état dans l'onglet publication.

Bien cordialement.

**Comment by garstud** [comment]
@sebastienlapoux je viens de verifier dans mon compte ...
Je n'arrive a pas tester correctement la correction !?

J'ai créé un article "test1":
* si il est en statut "non-publié", je ne peux pas le voir en cliquant sur le titre (err 404)
* si il est en statut "publié" avec une date de debut de publication dans le futur, je ne peux pas non plus le voir en cliquant sur le titre (err 404)

Pourtant ca devrait marcher, c'est ca ?

**Comment by garstud** [comment]
@sebastienlapoux ok merci je n'avais pas compris que cela ne marchait pas.
A voir si ca peut etre fait un jour car ce serait pratique ;) 

Après pour info, saches que sur Joomla (et je crois que cela date de Joomla 2.5) quand un auteur crée un article en "non-publié" il peut le voir sur le site avec un label "Dépublié" !
Je viens de refaire le test sur un site de dev :
![capture_2018-05-09_num01](https://user-images.githubusercontent.com/970021/39813096-6263f6f8-538f-11e8-91d3-291602b1ef21.png)

**Comment by sebastienlapoux** [comment]
Salut @garstud ,

Merci.
On ne tombe pas sur les mêmes résultats de test et peut être parlons nous pas de la même notion d'"auteur".

Dans un Joomla de base, un utilisateur assigné au groupe Author, une fois son article créé et dépublié ne peut pas voir son article. 

Pour voir son article en vue détail (ou vue liste Joomla), l'utilisateur doit avoir la permission d'éditer l'état (Edit State).
Dans les groupes Joomla de base, c'est seulement à partir du groupe Publisher que l'utilisateur à le droit d'éditer l'état.

Mais attention, le fait que l'utilisateur est le droit d'éditer l'état lui donne le droit de voir n'importe quel article dépublié et pas seulement les siens. Ce qui représente un important soucis de sécurité et confidentialité et n'est pas viable sur joomla.fr

Nous avons fait le test sur Joomla.fr et cela fonctionne en donnant le droit au niveau des articles Joomla mais l'avons retiré pour les raisons évoquées ci-dessus.

Nous cloturons le ticket pour l'instant.

Bien cordialement.
