### ISSUE TITLE
Moteur de recherche - Actualités

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#72]
Il semble que le moteur de recherche ne fonctionne pas; je ne vois pas de différences après avoir appliqué un filtre.

Par exemple, impossible de filtrer sur "Réunion du CA" ou juste "AFUJ"

![2018-06-01_09h52_49](https://user-images.githubusercontent.com/355999/40828693-9fb98730-6581-11e8-8f28-dfa8c53dec63.png)

**Comment by sebastienlapoux** [comment]
Bonjour @cavo789 ,

Le moteur de recherche fonctionne correctement selon sa configuration actuelle.

Il recherche dans le titre et le texte (description) d'un article : 
![image](https://user-images.githubusercontent.com/13470265/40843086-276d54e4-65b0-11e8-98ad-c6730056107c.png)

La recherche réalisé sur la chaine de caractère saisi est "Any Words" : 
![image](https://user-images.githubusercontent.com/13470265/40843133-4ef57136-65b0-11e8-8d9f-2fdc8109ff00.png)

Le Any Words cherche chacun des mots de la chaine.

Souhaites-tu un autre "match" : 
![image](https://user-images.githubusercontent.com/13470265/40843265-b00be3c4-65b0-11e8-858a-3159b1c9d8d1.png)
![image](https://user-images.githubusercontent.com/13470265/40843281-b9d867ec-65b0-11e8-80a1-edb04e736161.png)

Je l'ai changé pour l'instant sur "Permissive" qui semble plus correspondre à ce que tu cherches.

Bien cordialement.

**Comment by cavo789** [comment]
Merci pour ta réponse. 

Je comprends que ma recherche Réunion du CA recherche donc sur ces trois mots.

Je viens de tester "Réunion du CA" avec guillemets donc et cela ne change rien.

Mon besoin était de, facilement, afficher la liste des comptes-rendus ayant été publié.

Bonne journée

**Comment by sebastienlapoux** [comment]
> Je l'ai changé pour l'instant sur "Permissive" qui semble plus correspondre à ce que tu cherches.

Merci de tester à nouveau comme tu faisais auparavant.

**Comment by cavo789** [comment]
Devrais-je voir une différence ? Cela n'est pas le cas.

J'ai essayé Réunion du CA avec ou sans guillemets.

https://www.joomla.fr/actualites?seb_news_keywords=Réunion+du+CA
https://www.joomla.fr/actualites?seb_news_keywords="Réunion+du+CA"

(j'ai simplifié l'URL ci-dessus, l'URL complète reprends plusieurs autres paramètres)

Cette "issue" serait donc plus un "Feature request" dans le sens "Rechercher plusieurs mots consécutifs" comme on peut le faire avec Google.

Bonne soirée

**Comment by sebastienlapoux** [comment]
Je ne comprends pas @cavo789 .
Tu parles du gestionnaire Mes actualités (ou gestionnaire Actualité dans admin) ou bien de la vue public qui liste les actualités ?

**Comment by sebastienlapoux** [comment]
j'ai donc aussi changé le match en "permissive" sur la vue public actualité https://www.joomla.fr/actualites?seb_news_keywords=r%C3%A9union+du+CA&seb_news_ordering=art_created%3Adesc&boxchecked=0&search=seb_news&task=search

**Comment by cavo789** [comment]
Merci, parfait !
