### ISSUE TITLE
problème affichage image d'intro des articles

### ISSUE THREAD

**Issue by cocorosierosie** [AFUJ/joomla.fr#74]
Bonjour,
Suite aux dernières mises à jour joomla, plus aucun de mes images d'intro ne s'affichent, il y a donc une page blanche...
Ma version est 3.8.10.
Le lien vers mon site avec l'erreur : http://kravmaganormandie.com/grades
le même lien en backend, montrant que l'image est bien présente.

C'est très gênant car mon site n'est plus fonctionnel en l'état. Quelle est la solution ?

Cordialement,
Corinne
![erreur image intro backend](https://user-images.githubusercontent.com/40715772/42124795-8d6ea5c0-7c69-11e8-821f-d82171824ecb.PNG)
![erreur image intro](https://user-images.githubusercontent.com/40715772/42124796-8d9df492-7c69-11e8-93c1-6facb4e15757.PNG)

**Comment by cavo789** [comment]
Bonjour,

Merci pour votre requête concernant Joomla!, logiciel Open Source et gratuit vous permettant de créer votre site web.

Nous vous invitons à poser toute demande de support auprès de la forte communauté francophone Joomla! sur notre forum (https://forum.joomla.fr) et, si vous souhaitez passer par un prestataire, plus spécialement sur le forum “Demande de service” (https://forum.joomla.fr/forumdisplay.php?84-Demande-de-service). Si vous n’avez pas encore de compte utilisateur, il vous faudra au préalable en créer un avant de pouvoir publier votre message (https://forum.joomla.fr/register.php).

Note : l’Association Francophone des Utilisateurs de Joomla! (AFUJ) est une association de bénévoles oeuvrant pour la reconnaissance de Joomla! et est notamment en charge du site français https://www.joomla.fr. L’AFUJ n’est pas un prestataire de services.

Bien cordialement,

L’équipe de l’AFUJ

https://www.joomla.fr
