### ISSUE TITLE
Absence de formulaire de contact 

### ISSUE THREAD

**Issue by YGomiero** [AFUJ/joomla.fr#75]
https://www.joomla.fr/contact

Que l'on soit identifié ou non,  la sélection n'affiche aucun formulaire pour aide, asso, jug, partenariat...
Il faut choisir "autre" en espérant que cela fonctionne ce qui n'est pas evident pour les débutants.

**Comment by YGomiero** [comment]
Je profite du problème pour poser la question des choix forum et annuaire pro au premier plan.
Pourquoi ce n'est pas intégré au formulaire  ? Pourquoi il n'y a pas d'informations lié à la réglementation européenne dans la page contact (obligatoire depuis le 25 mai 2018) ?

**Comment by sebastienheraud** [comment]
Bonjour,

> Que l'on soit identifié ou non, la sélection n'affiche aucun formulaire pour aide, asso, jug, partenariat...
> Il faut choisir "autre" en espérant que cela fonctionne ce qui n'est pas evident pour les débutants.

Ce point est fixé (regression).

Cordialement,
