### ISSUE TITLE
erreur "Message Il n'y a pas de résultat." sur page accueil joomla.fr

### ISSUE THREAD

**Issue by YGomiero** [AFUJ/joomla.fr#76]
Sur firefox et chrome, la page d'accueil affiche un message étrange : 

![screenshot_1](https://user-images.githubusercontent.com/1731681/44026098-4b8874b4-9ef2-11e8-9d6c-5b400533e849.jpg)

" Message Il n'y a pas de résultat. "

Il s'affiche que l'on soit identifié ou non.

**Comment by sebastienlapoux** [comment]
Si tu es identifié ?

**Comment by YGomiero** [comment]
non, j'ai vidé le cache, cookies, etc... 

![screenshot_2](https://user-images.githubusercontent.com/1731681/44026721-4f455b10-9ef4-11e8-9708-faa6cefa9a2f.jpg)

**Comment by sebastienlapoux** [comment]
@YGomiero , fixé, merci ! Etait du au fait que plus d'évènement à afficher en home.
