### ISSUE TITLE
Images dans les articles

### ISSUE THREAD

**Issue by sebastienlapoux** [AFUJ/joomla.fr#77]
Bonjour @agerix @com3elles @cavo789 ,

En cliquant sur le bouton "Retailler" d'une image dans le formulaire de soumission d'un article : 
![image](https://user-images.githubusercontent.com/13470265/45016457-fd502780-b024-11e8-8a86-45b21a2e9ee2.png)

Il faut retailler l'image pour la vue article (détail d'un article) et la vue liste : 
![image](https://user-images.githubusercontent.com/13470265/45016521-28d31200-b025-11e8-923f-89871e261889.png)

Exemple de l'image en vue article
![image](https://user-images.githubusercontent.com/13470265/45016590-63d54580-b025-11e8-89ac-15132a2dcec6.png)

Exemple de l'image en vue liste
![image](https://user-images.githubusercontent.com/13470265/45016629-7cddf680-b025-11e8-9aab-4515dfb3787f.png)

Sur la vue liste nous conseillons d'ajouter un fond noir lorsque  l'image est trop petite ou pas aux bonnes dimensions en sélectionnant la couleur ainsi :  
![image](https://user-images.githubusercontent.com/13470265/45016699-bf9fce80-b025-11e8-898f-8fc7ae1898e2.png)

Bien cordialement.

**Comment by cavo789** [comment]
Merci Sébastien. 

J'ai repris un lien vers cette information dans un tutoriel "Comment publier sur le portail" à destination des personnes du groupe GT009 - Publication. Ce tutoriel est accessible dans notre interface de documentation.

**Comment by sebastienlapoux** [comment]
Génial ! Merci @cavo789
