### ISSUE TITLE
Document dans un article non accessible

### ISSUE THREAD

**Issue by com3elles** [AFUJ/joomla.fr#79]
Bonjour,
j'ai voulu mettre un pdf à télécharger dans cet événement https://www.joomla.fr/evenements/site-internet-questions-reponses
Quand on clique dessus pour l'ouvrir, ça affiche "Erreur Vous n'êtes pas autorisé à accéder à ce fichier."

**Comment by lionelratel** [comment]
Bonjour @com3elles,  
c'est corrigé.  

Peux tu confirmer que c'est ok pour toi ?

Cordialement.

**Comment by com3elles** [comment]
Je confirme ! Merci pour la réactivité !
Bonne journée
