### ISSUE TITLE
Adhésion - Nouveau compte - ERREUR

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#8]
Note : il y a encore des textes en blanc, peu lisible

![2018-02-26_18h40_40](https://user-images.githubusercontent.com/355999/36685741-8dd285e6-1b24-11e8-884f-1f58f960a1e6.png)

**Comment by cavo789** [comment]
Je viens de recommencer, j'ai tenté "JTest_ Nouveau@didp.fr" et cela bloque encore, je reteste et toujorus KO.

L'utilisateur JTest_ Nouveau@didp.fr ne passe pas du tout.

**Comment by cavo789** [comment]
Je tente encore, avec d'autres données, cela passe (même IP)
![2018-02-26_18h44_51](https://user-images.githubusercontent.com/355999/36685961-3618f71c-1b25-11e8-926c-71866f638fe5.png)

**Comment by sebastienlapoux** [comment]
@cavo789 merci pour des précisions. 
Que testes-tu ? L'email ? L'email JTest_ Nouveau@didp.fr contient un espace

**Comment by sebastienlapoux** [comment]
faire des tests de création de compte sans l'envoi d'email activé n'a que peu de sens. Il aurait fallu d'abord nous demander d'activer l'envoi d'email.
Merci ce reporter tes tests à demain sur le site en production.

**Comment by cavo789** [comment]
Non pas d'espace

**Comment by sebastienlapoux** [comment]
Tester à nouveau en prod avec identifiant email et email reçu. Tout ok.

Nous fermons ce ticket, merci d'en ouvrir un autre si cela se reproduit.
