### ISSUE TITLE
Styles "boites" de l'editeur d'article inutilisables

### ISSUE THREAD

**Issue by garstud** [AFUJ/joomla.fr#83]
Bonjour,
J'ai essayé d'utiliser les styles de "boites" proposé dans le #45 et dans l'article "Exemple de mise en page" ... en vain.
J'ai l'impression que l'editeur nettoie les balises lors de l'enregistrement, du coup les div class="box" et leurs styles sont perdus lors de l'enregistrement.

J'ai voulu utiliser un style Box sur l'article "JOOMLA 4 EN APPROCHE..." qui va sortir ce midi, il reste juste un "div class=box" mais les attributs sont perdus a chaque enregistrement de l'article.

- y a t-il une solution pour utiliser ces styles ?
Merci.

**Comment by sebastienlapoux** [comment]
Bonjour @garstud ,

Je te remercie !
JCE a été installé sans que la personne l'ayant fait soit en connaissance de cause, alors que le site a été conçu avec Tiny.

Nous sommes repassé sur Tiny et tu devrais retrouver tes petits.

Merci pour ta confirmation.

Bien cordialement.

**Comment by garstud** [comment]
En fait je crois que j'ai pisté le probleme.
les styles proposés dans l'editeur ajoute le code :
`<div class="box" data-box-color="blue">`

alors que pour ca marche il faut :
`<div class="box" data-box-style="8">`

Merci a celui qui a changé mon editeur, j'ai pu le saisir manuellement ;) ca marche.
Je vous laisse voir si vous pouvez corriger les styles pre-programmés.

**Comment by garstud** [comment]
Ok, merci @sebastienlapoux  ;) 

par contre avec Tiny, on a plus les styles et format présentés dasn l'article "Exemple de mise en page" !?
JCE n'a pas été justement utilisé pour ces styles ?

**Comment by sebastienlapoux** [comment]
ok marc, problème de droit, merci de me dire si tu vois maintenant comme moi (image ci-dessus)

**Comment by garstud** [comment]
Je viens de verifier.
J'ai désormais bien accès a "Formats > Container > Styles"

Et effectivement, en choisissant d'abord "Formats > Containers > Container" puis le style voulu, ca marche.

Super, merci @sebastienlapoux pour ta diligence ;)
