### ISSUE TITLE
Bug pour renouveler l'adhésion à l'association : "error in your SQL syntax"

### ISSUE THREAD

**Issue by easyconnect83** [AFUJ/joomla.fr#85]
Bonjour j'ai voulu renouveler mon adhésion à l'Afuj et au moment de valider le formulaire la formule d'adhésion "professionnel de Joomla!" j'ai ce message d'erreur ci-dessous :

Je précise que j'étais déjà connecté sur mon compte et que j'ai coché l'option "renouvellement". 

Bonne journée!.

![adhésion afuj](https://user-images.githubusercontent.com/36700921/130802085-f1554e39-4932-43b5-a7ec-662431e956ae.JPG)

**Comment by sebastienlapoux** [comment]
Bonjour,

Merci ! Nous connaissons la cause et la résolution. Nous revenons vers vous.

Bien cordialement.

**Comment by sebastienlapoux** [comment]
Bonjour @easyconnect83 ,

Le problème est corrigé. Merci de confirmer si ok.

Bien cordialement.

**Comment by easyconnect83** [comment]
C'est rapide ! Merci pour votre réactivité Sébastien. J'ai pu confirmer et payer le renouvellement de l'adhésion.
Bonne continuation.

Encore merci!
Bien cordialement.
