### ISSUE TITLE
Lien Paypal pour le paiement de la cotisation

### ISSUE THREAD

**Issue by CybSnoopy** [AFUJ/joomla.fr#86]
Bonjour !

Juste un mot pour vous signaler que le lien auquel renvoie le bouton "Connectez-vous" sur l'onglet "Connectez-vous à votre compte Paypal" renvoie au login général Paypal et non au login de paiement (avec indication du montant et du destinataire), ce qui n'est vraiment pas pratique.

Bonne journée !

Snoopy
![Screen Shot 09-23-21 at 11 07 AM](https://user-images.githubusercontent.com/75395934/134482821-37c58b5a-2027-47b4-8e74-8f6c16de8e9c.PNG)

**Comment by sebastienlapoux** [comment]
Bonjour @CybSnoopy,

Merci. Après un test réel, j'ai bien été renvoyé sur la page ci-dessous après m'être connecté (avec double authentification, SMS).

![image](https://user-images.githubusercontent.com/13470265/134522915-03980207-8419-48dc-9225-66c15c4c0485.png)

Si problème dans certains cas, problème côté Paypal que nous ne pouvons pas régler.

Je cloture.

Encore merci.

Bien cordialement.
