### ISSUE TITLE
Nouveau compte validé, titre "Listen" et menu allégé

### ISSUE THREAD

**Issue by cavo789** [AFUJ/joomla.fr#9]
Juste après la validation du compte, le titre de la page est Listen et le menu est plutôt pauvre.

![2018-02-26_18h46_20](https://user-images.githubusercontent.com/355999/36686046-66a034d6-1b25-11e8-87b0-88849dc3a1f3.png)

Je fais juste CTRL-F5 (rien d'autre) et là j'ai un menu plus complet.

![2018-02-26_18h47_40](https://user-images.githubusercontent.com/355999/36686085-861ac86c-1b25-11e8-8857-399ebc773197.png)

**Comment by lionelratel** [comment]
Test éffectué sur le dev sans passé par paypal.  
Merci de refaire le test sur la prod.
